### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by MarkCockerill12** [MarkCockerill12/GroupAPIProject-TheBestOne-Grp8#11]
make it respond to different webpage sizes, possible change colour when hovering mouse over / change elements of the page

**Comment by Tonytct** [comment]
Made a basic Navbar and add bootstrap 5.2.3 to the website. The website navbar is now responsive. When the page gets small it will switch to a button.

**Comment by MarkCockerill12** [comment]
good stuf
